{
 "title": "Raspberry's metrics",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "1m",
 "panels": [
  {
   "title": "ARM's frequency",
   "type": "stat",
   "gridPos": { "h": 12, "w": 9, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "rothz" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "rpi_metrics_arm_freq", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "ARM's temperature",
   "type": "stat",
   "gridPos": { "h": 12, "w": 9, "x": 9, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "rpi_metrics_soc_temp", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Voltage",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 18, "x": 0, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "volt" } },
   "targets": [
    { "expr": "rpi_metrics_core_volts", "legendFormat": "__auto" }
   ]
  }
 ]
}