version: '3.8'

services:
  mosquitto:
    image: ${PRIVATE_REPO}/eclipse-mosquitto:2.0.22-openssl
    deploy:
      mode: global  # Ensures one instance per eligible node
      restart_policy:
        condition: on-failure
      resources:
        limits:
          memory: 100M
          cpus: "1"
      placement:
        constraints:
          - node.labels.mqtt == true
    networks:
      - public-network
    ports:
      - "1883:3881"
    volumes:
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
      - /etc/hostname:/etc/hostname:ro
      - /data/mosquitto/data:/mosquitto/data
      - /data/mosquitto/log:/mosquitto/log


networks:
  public-network:
    driver: overlay
    internal: true   # isolates backend traffic