version: '3.8'

services:

#################################
#                               #
#          P A R T   4          #
#                               #
#################################

  hivemq-edge:
    image: ${PRIVATE_REPO}/hivemq/hivemq-edge:2025.8
    deploy:
      mode: global  # Ensures one instance per eligible node
      restart_policy:
        condition: on-failure
      resources:
        limits:
          memory: 100M
          cpus: "1"
      placement:
        constraints:
          - node.labels.mqtt == true
    ports:
      - "5001:5100"
    volumes:
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
      - /etc/hostname:/etc/hostname:ro


#################################
#                               #
#          P A R T   5          #
#                               #
#################################
  telegraf-level0:
    image: ${PRIVATE_REPO}/telegraf-level0:1.34.4-alpine
    deploy:
      mode: global  # Ensures one instance per eligible node
      restart_policy:
        condition: on-failure
      resources:
        limits:
          memory: 100M
          cpus: "1"
      placement:
        constraints:
          - node.labels.level == 0
    volumes:
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
      - /etc/hostname:/etc/hostname:ro
      - /data/telegraf:/telegraf
      # For Docker
      - /var/run/docker.sock:/var/run/docker.sock:ro
      # File system
      - /proc/sys/fs:/host/proc/sys/fs:ro
      # For CPU metrics
      - /proc/stat:/proc/stat:ro
      - /proc/cpuinfo:/proc/cpuinfo:ro
      # For memory metrics
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro

  telegraf-level1:
    image: ${PRIVATE_REPO}/telegraf-level1:1.34.4-alpine
    deploy:
      mode: global  # Ensures one instance per eligible node
      restart_policy:
        condition: on-failure
      resources:
        limits:
          memory: 100M
          cpus: "1"
      placement:
        constraints:
          - node.labels.level == 1
    volumes:
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
      - /etc/hostname:/etc/hostname:ro
      - /data/telegraf:/telegraf
      # For Docker
      - /var/run/docker.sock:/var/run/docker.sock:ro
      # For CPU metrics
      - /proc/stat:/proc/stat:ro
      - /proc/cpuinfo:/proc/cpuinfo:ro
      # For memory metrics
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro

  telegraf-level2:
    image: ${PRIVATE_REPO}/telegraf-level2:1.34.4-alpine
    deploy:
      mode: global  # Ensures one instance per eligible node
      restart_policy:
        condition: on-failure
      resources:
        limits:
          memory: 100M
          cpus: "1"
      placement:
        constraints:
          - node.labels.level == 2
    volumes:
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
      - /etc/hostname:/etc/hostname:ro
      - /data/telegraf:/telegraf
      # For Docker
      - /var/run/docker.sock:/var/run/docker.sock:ro
      # For CPU metrics
      - /proc/stat:/proc/stat:ro
      - /proc/cpuinfo:/proc/cpuinfo:ro
      # For memory metrics
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      # For temperature metrics
      - /sys/class/thermal:/sys/class/thermal:ro
      # For vcgencmd metrics
      - /tmp/telegraf_metrics:/telegraf_metrics:ro


#################################
#                               #
#          P A R T   6          #
#                               #
#################################


  vminsert:
    image: ${PRIVATE_REPO}/victoriametrics/vminsert:v1.119.0-cluster
    deploy:
      mode: replicated
      replicas: 2
      restart_policy:
        condition: on-failure
      placement:
        constraints:
          - node.labels.level == 0
    command:
      - '--storageNode=vmstorage:8400'
    depends_on:
      - vmstorage
    ports:
      - "8480:8480"  # remote_write endpoint for Telegraf
    volumes:
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
      - /etc/hostname:/etc/hostname:ro

  vmstorage:
    image: ${PRIVATE_REPO}/victoriametrics/vmstorage:v1.119.0-cluster
    deploy:
      mode: global
      restart_policy:
        condition: on-failure
      placement:
        constraints:
          - node.labels.level == 0
    command:
      - '--retentionPeriod=1d'
      - '--storageDataPath=/vmstorage'
    volumes:
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
      - /etc/hostname:/etc/hostname:ro
      - /data/victoriametrics:/vmstorage

  vmselect:
    image: ${PRIVATE_REPO}/victoriametrics/vmselect:v1.119.0-cluster
    deploy:
      mode: replicated
      replicas: 2 
      restart_policy:
        condition: on-failure
      placement:
        constraints:
          - node.labels.level == 0
    depends_on:
      - vmstorage
    ports:
      - "8481:8481"  # UI and query API
    volumes:
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
      - /etc/hostname:/etc/hostname:ro
    command:
      - '--storageNode=vmstorage:8401'


  vmauth:
    image: ${PRIVATE_REPO}/victoriametrics/vmauth:v1.119.0
    deploy:
      mode: replicated
      replicas: 1
      restart_policy:
        condition: on-failure
      placement:
        constraints:
          - node.labels.level == 0
    depends_on:
      - vmselect
    ports:
      - "8428:8428"
    volumes:
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
      - /etc/hostname:/etc/hostname:ro


#################################
#                               #
#          P A R T   7          #
#                               #
#################################


  alloy-alllevels:
    image: ${PRIVATE_REPO}/grafana/alloy:v1.9.1
    deploy:
      mode: global  # Ensures one instance per eligible node
      replicas: 1
      restart_policy:
        condition: on-failure
    ports:
      - "3100:3100"
    volumes:
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
      - /etc/hostname:/etc/hostname:ro
      - /data/alloy:/alloy
